{%- import 'macros/integration.yaml' as integration %}
{%- import 'macros/de-novo-env.yaml' as de_novo_env %}
{%- import 'macros/env-file.yaml' as env_file %}
{%- import 'macros/merge-env-files.yaml' as merge_env_files %}
{%- import 'macros/unit-test.yaml' as unit_test %}
groups:
  - name: test
    jobs:
      - batch-builds-together
      - create-testing-env-files
      {%- for project in projects %}
      - unit-test-{{ project.name }}
      {%- endfor %}
      - integration
  - name: stage
    jobs:
      {%- for project in projects %}
      - stage-{{ project.name }}
      {%- endfor %}
      - batch-uploads-together
      - create-staging-env-files
  - name: release
    jobs:
      {%- for project in projects %}
      - release-{{ project.name }}
      {%- endfor %}
      - create-release-env-files
  - name: all
    jobs:
      {%- for project in projects %}
      - stage-{{ project.name }}
      - release-{{ project.name }}
      {%- endfor %}
      - batch-builds-together
      - integration
      - batch-uploads-together
      - create-testing-env-files
      - create-staging-env-files
      - create-release-env-files

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: master

  - name: throttle-timer
    type: time
    source:
      interval: 10m

  - name: docs-source
    type: git
    check_every: 2m
    source:
      uri: https://github.com/{{ defaults.github_org }}/docs
      branch: {{ defaults.release_branch }}

  - name: environment-files
    type: git
    check_every: 10m
    source:
      uri: https://github.com/qiime2/environment-files
      branch: master
      username: ((github_user))
      password: ((github_pass))

  - name: test-environment-files
    type: git
    check_every: 10m
    source:
      uri: https://github.com/qiime2/environment-files
      branch: master
      username: ((github_user))
      password: ((github_pass))
      paths:
        - {{ defaults.release }}/test/*

  {%- for project in projects %}
  - name: {{ project.name }}-{{ project.release }}-test-channel
    type: conda-channel
    check_every: 10m
    source:
      pkg_name: {{ project.name }}
      uri: https://packages.qiime2.org/qiime2
      channel: {{ project.test_channel }}
      # TODO: undo when reverting tag-dev.sh changes
      regex: ^{{ project.release|replace('.', '\.') }}\.[0-9]\.dev2+
      matched: [osx-64, linux-64]

  - name: {{ project.name }}-{{ project.release }}-staging-channel
    type: conda-channel
    check_every: 10m
    source:
      pkg_name: {{ project.name }}
      uri: ((staging_uri))
      channel: {{ project.staging_channel }}
      user: ((staging_user))
      pass: ((staging_pass))
      # TODO: undo when reverting tag-dev.sh changes
      regex: ^{{ project.release|replace('.', '\.') }}\.[0-9]\.dev2+
      matched: [osx-64, linux-64]

  - name: {{ project.name }}-{{ project.release }}-release-staging-channel
    type: conda-channel
    check_every: 5m
    source:
      pkg_name: {{ project.name }}
      uri: https://packages.qiime2.org/qiime2
      channel: {{ project.staging_channel }}
      # Emrakool approves
      regex: ^{{ project.release|replace('.', '\.') }}\.[0-9]+$
      matched: [osx-64, linux-64]

  - name: {{ project.name }}-{{ project.release }}-release-channel
    type: conda-channel
    check_every: 10m
    source:
      pkg_name: {{ project.name }}
      uri: https://conda.anaconda.org
      channel: {{ project.release_channel }}
      user: ((anaconda_user))
      pass: ((anaconda_pass))
      matched: [osx-64, linux-64]
  {% endfor %}
jobs:
  {%- for project in projects %}
  - name: stage-{{ project.name }}
    public: true
    plan:
      - get: {{ project.name }}-{{ project.release }}-test-channel
        trigger: true
        passed: [integration]
      - put: {{ project.name }}-{{ project.release }}-staging-channel
        params:
          from: {{ project.name }}-{{ project.release }}-test-channel

  - name: release-{{ project.name }}
    public: true
    plan:
      - get: {{ project.name }}-{{ project.release }}-release-staging-channel
        trigger: true
      - put: {{ project.name }}-{{ project.release }}-release-channel
        params:
          from: {{ project.name }}-{{ project.release }}-release-staging-channel

  - name: unit-test-{{ project.name }}
    public: true
    plan:
      - get: busywork
      - get: {{ project.name }}-{{ project.release }}-test-channel
        trigger: true
        passed: [create-testing-env-files]
      {%- for dep in project.deps %}
      - get: {{ dep.name }}-{{ dep.release }}-test-channel
        trigger: true
        {%- if dep.testable %}
        passed: [unit-test-{{ dep.name }}]
        {%- endif %}
      {%- endfor %}
      - aggregate:
        - task: test-linux
          config:
            {{- unit_test.make_linux_config(project, defaults)|indent(12) }}
        - task: test-darwin
          attempts: 2
          config:
            {{- unit_test.make_darwin_config(project, defaults)|indent(12) }}
  {% endfor %}
  - name: batch-builds-together
    public: true
    build_logs_to_retain: 50
    plan:
      - get: throttle-timer
        trigger: true
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-test-channel
      {%- endfor %}

  - name: create-testing-env-files
    serial_groups: [create-env-files]
    public: true
    max_in_flight: 1
    plan:
      - get: busywork
      - get: environment-files
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-test-channel
        trigger: true
        passed: [batch-builds-together]
      {%- endfor %}
      - aggregate:
        - task: test-env-file-linux
          config:
            {{- de_novo_env.make_linux_config(projects, defaults)|indent(12) }}
        - task: test-env-file-darwin
          config:
            {{- de_novo_env.make_darwin_config(projects, defaults)|indent(12) }}
      - task: merge-and-commit-env-files
        config:
          {{- merge_env_files.make_config("test", defaults)|indent(10) }}
      - put: environment-files
        params:
          repository: updated-environment-files
          rebase: true

  - name: integration
    public: true
    max_in_flight: 1
    plan:
      - get: busywork
      - get: environment-files
        trigger: true
        resource: test-environment-files
      - get: docs-source
        trigger: true
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-test-channel
        passed: [unit-test-{{ project.name }}]
      {%- endfor %}
      - aggregate:
        - task: integration-linux
          config:
            {{- integration.make_linux_config(projects, sorted_projects, defaults)|indent(12) }}
        - task: integration-darwin
          config:
            {{- integration.make_darwin_config(projects, sorted_projects, defaults)|indent(12) }}

  - name: batch-uploads-together
    public: true
    build_logs_to_retain: 50
    plan:
      - get: throttle-timer
        trigger: true
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-staging-channel
        passed: [stage-{{ project.name }}]
      {%- endfor %}

  - name: create-staging-env-files
    serial_groups: [create-env-files]
    public: true
    plan:
      - get: busywork
      - get: environment-files
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-staging-channel
        trigger: true
        passed: [batch-uploads-together]
      {%- endfor %}
      - aggregate:
        - task: staging-env-file-linux
          config:
            {{- env_file.make_linux_config(projects, defaults, "staging-channel")|indent(12) }}
        - task: staging-env-file-darwin
          config:
            {{- env_file.make_darwin_config(projects, defaults, "staging-channel")|indent(12) }}
      - task: merge-and-commit-env-files
        config:
          {{- merge_env_files.make_config("staging", defaults)|indent(10) }}
      - put: environment-files
        params:
          repository: updated-environment-files
          rebase: true

  - name: create-release-env-files
    serial_groups: [create-env-files]
    public: true
    plan:
      - get: busywork
      - get: environment-files
      {%- for project in projects %}
      - get: {{ project.name }}-{{ project.release }}-release-channel
        trigger: true
        passed: [release-{{ project.name }}]
      {%- endfor %}
      - aggregate:
        - task: release-env-file-linux
          config:
            {{- env_file.make_linux_config(projects, defaults, "release-channel")|indent(12) }}
        - task: release-env-file-darwin
          config:
            {{- env_file.make_darwin_config(projects, defaults, "release-channel")|indent(12) }}
      - task: merge-and-commit-env-files
        config:
          {{- merge_env_files.make_config("release", defaults)|indent(10) }}
      - put: environment-files
        params:
          repository: updated-environment-files
          rebase: true

resource_types:
  - name: conda-channel
    type: docker-image
    source:
      repository: quay.io/qiime2/conda-channel-resource
