---
{%- import 'macros/tag-release.yaml' as tag_release %}
{%- import 'macros/tag-dev.yaml' as tag_dev %}

# TODO:
#   - Make rendered yaml pretty! It's all over the place right now.
#   - Can we use pyyaml instead of jinja2 to generate these configs?
groups:
  - name: tag-dev
    jobs:
      - devit
      {%- for project in projects %}
      - tag-{{ project.name }}-dev
      {%- endfor %}
  - name: tag-release
    jobs:
      - shipit
      {%- for project in projects %}
      - tag-{{ project.name }}-release
      {%- endfor %}

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: master

  {%- for project in projects %}
  - name: {{ project.name }}-source
    type: git
    source:
      uri: https://github.com/{{ project.github_org }}/{{ project.name }}
      branch: {{ project.release_branch }}
      username: ((github_user))
      password: ((github_pass))
  {%- endfor %}

jobs:
  - name: shipit
    plan:
      - get: busywork

  - name: devit
    plan:
      - get: busywork

  {%- for project in projects %}
  - name: tag-{{ project.name }}-release
    plan:
      - get: busywork
        trigger: true
        passed: [shipit]
      - get: {{ project.name }}-source
      - task: tag-release
        config:
          {{- tag_release.make_config(project)|indent(10) }}
      - put: {{ project.name }}-source
        params:
          repository: tagged-{{ project.name }}-source
          tag: tagged-{{ project.name }}-source/tag
          annotate: tagged-{{ project.name }}-source/annotate

  - name: tag-{{ project.name }}-dev
    plan:
      - get: busywork
        trigger: true
        passed: [devit]
      - get: {{ project.name }}-source
      - task: tag-dev
        config:
          {{- tag_dev.make_config(project)|indent(10) }}
      - put: {{ project.name }}-source
        params:
          repository: tagged-{{ project.name }}-source
          tag: tagged-{{ project.name }}-source/tag
          annotate: tagged-{{ project.name }}-source/annotate
  {%- endfor %}
