---

- name: install concourse binary
  get_url:
    url: "{{ concourse_download_url }}"
    dest: /usr/local/bin/concourse
    mode: u+x
    force: yes

- name: create concourse working directory
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items:
    - { path: "{{ base_dir }}/{{ keys_dir }}", state: directory }
    - { path: "{{ base_dir }}/{{ log_dir }}", state: directory }
    - { path: "{{ base_dir }}/{{ log_dir }}/concourse.stdout", state: touch }
    - { path: "{{ base_dir }}/{{ log_dir }}/concourse.stderr", state: touch }

- name: copy keys, plist, worker script
  copy:
    src: "{{ tsa_keys }}/{{ item }}"
    dest: "{{ base_dir }}/{{ keys_dir }}"
  with_items:
    - tsa_host_key.pub
    - worker_key

- template:
    src: run_worker.sh
    dest: "{{ base_dir }}"
    mode: u+x

- name: copy plist
  template:
    src: org.qiime2.concourse.plist
    dest: /Library/LaunchDaemons/
    owner: root
    group: wheel
  become: true

- name: unload launchctl
  shell: launchctl unload /Library/LaunchDaemons/org.qiime2.concourse.plist
  become: true

- name: load launchctl
  shell: launchctl load /Library/LaunchDaemons/org.qiime2.concourse.plist
  become: true
