{%- import 'macros/copy-templates.yaml' as copy %}
{%- import 'macros/update-copyright.yaml' as copyright %}

resources:
  - name: busywork
    type: git
    source:
      uri: https://github.com/qiime2/busywork
      branch: master

  - name: template-repo-labels
    type: git
    check_every: 2m
    source:
      uri: https://github.com/qiime2/template-repo
      branch: master
      paths:
        - labels/*

  - name: template-repo-templates
    type: git
    check_every: 2m
    source:
      uri: https://github.com/qiime2/template-repo
      branch: master
      paths:
        - github_templates/*

  - name: template-repo-copyright
    type: git
    check_every: 2m
    source:
      uri: https://github.com/qiime2/template-repo
      branch: master
      paths:
        - copyright/*
        - common/*

  {%- for repo in repos %}
  - name: {{ repo.name }}-source
    type: git
    check_every: 24h
    source:
      uri: https://github.com/qiime2/{{ repo.name }}
      branch: master
      username: ((github_user))
      password: ((github_pass))
  {%- endfor %}

jobs:
  - name: copyrightit
    plan:
      - get: busywork

  - name: sync-labels
    public: true
    plan:
      - get: busywork
      - get: template-repo
        resource: template-repo-labels
        trigger: true
      - task: sync-labels
        file: busywork/extra/github/tasks/copy-labels.yaml
        params:
          GITHUB_USER: ((github_user))
          GITHUB_PASS: ((github_pass))
          REPOS: {{ ' '.join(repos) }}  # space is in $IFS for looping

  {%- for repo in repos %}
  - name: sync-{{ repo.name }}-templates
    public: true
    plan:
      - get: busywork
      - get: template-repo
        resource: template-repo-templates
        trigger: true
      - get: {{ repo.name }}-source
      - task: sync-templates
        config:
          {{- copy.make_linux_config(repo)|indent(10) }}
      - put: {{ repo.name }}-source
        params:
          repository: {{ repo.name }}-source-updated
          rebase: true

  - name: update-{{ repo.name }}-copyright
    public: true
    plan:
      - get: busywork
        trigger: true
        passed: [copyrightit]
      - get: template-repo
        resource: template-repo-copyright
        trigger: false
      - get: {{ repo.name }}-source
      - task: update-copyright
        config:
          {{- copyright.make_linux_config(repo.name)|indent(10) }}
      - put: {{ repo.name }}-source
        params:
          repository: {{ repo.name }}-source-updated
          rebase: true
  {%- endfor %}
