---

- name: make concourse web keys dir
  file:
    name: "{{ base_dir }}/{{ keys_dir }}"
    state: directory

- name: copy keys
  copy:
    src: "{{ tsa_keys }}/{{ item }}"
    dest: "{{ base_dir }}/{{ keys_dir }}"
  with_items:
    - tsa_host_key.pub
    - worker_key

- name: copy worker docker compose template
  template:
    src: linux_worker.yml
    dest: "{{ base_dir }}"

- name: deploy concourse worker containers
  become: True
  command: docker-compose -f {{ base_dir }}/linux_worker.yml up -d
  register: dc
  changed_when: '"Creating concourse_worker_1" in dc.stderr'
