---

- name: make concourse web keys dir
  file:
    name: "{{ base_dir }}/{{ keys_dir }}"
    state: directory

- name: copy keys
  copy:
    src: "{{ tsa_keys }}/{{ item }}"
    dest: "{{ base_dir }}/{{ keys_dir }}"
  with_items:
    - tsa_host_key
    - tsa_host_key.pub
    - worker_key
    - worker_key.pub

- name: session signing key
  shell: ssh-keygen -t rsa -N '' -f {{ base_dir }}/{{ keys_dir }}/session_signing_key -C session_signer
  args:
    creates: "{{ base_dir }}/{{ keys_dir }}/session_signing_key"

- name: set up authorized keys
  copy:
    src: "{{ base_dir }}/{{ keys_dir }}/worker_key.pub"
    dest: "{{ base_dir }}/{{ keys_dir }}/authorized_worker_keys"
    remote_src: True

- name: copy atc docker compose template
  template:
    src: atc.yml
    dest: "{{ base_dir }}"

- name: start atc and pg containers
  become: True
  command: docker-compose -f {{ base_dir }}/atc.yml up -d
  register: dc
  changed_when: '"Creating concourse_db_1" in dc.stderr and "Creating concourse_web_1" in dc.stderr'

- name: copy nginx configuration
  become: True
  template:
    src: external_host.conf
    dest: /etc/nginx/sites-available/{{ external_host }}.conf
  notify:
    - stop nginx
    - start nginx

- name: link nginx configuration
  become: True
  file:
    src: /etc/nginx/sites-available/{{ external_host }}.conf
    dest: /etc/nginx/sites-enabled/{{ external_host}}
    state: link
  notify:
    - stop nginx
    - start nginx
