# Linux
{%- macro make_linux_config(project, defaults) %}
platform: linux
image_resource:
  type: docker-image
  source:
    repository: quay.io/condaforge/linux-anvil-comp7
    tag: latest
params:
  PATH: /opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
inputs:
  - name: busywork
  - name: {{ project.name }}-source
    path: source
  {%- for dep in project.deps %}
  - name: {{ dep.name }}-{{ dep.release }}-test-channel
  {%- endfor %}
outputs:
  - name: build-linux
run:
  path: busywork/ci/{{ defaults.release_branch }}/bin/build.sh
{%- endmacro %}

# Darwin
{%- macro make_darwin_config(project, defaults) %}
platform: darwin
params:
  PATH: /Users/caporasolab/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  ACTIVATE_BASE_ENV: /Users/caporasolab/miniconda3/etc/profile.d/conda.sh
inputs:
  - name: busywork
  - name: {{ project.name }}-source
    path: source
  {%- for dep in project.deps %}
  - name: {{ dep.name }}-{{ dep.release }}-test-channel
  {%- endfor %}
outputs:
  - name: build-darwin
run:
  path: busywork/ci/{{ defaults.release_branch }}/bin/build.sh
{%- endmacro %}
